Implement slice subscription and assignment
SeedV/SeedLang pull request #197
Opened 2022-05-21 05:12 UTC by codingpotato

Fix #168 

`examples/seedpython/scripts/slice.py` and `examples/seedpython/scripts/sorting/merge_sort.py` can be run by SeedLang.Shell except `i = j = k = 0` is not support now (will submit another issue for that).

2022-05-21 13:48 UTC, wixette requested changes
Problems are found when float numbers are used as stop-index or step.

Problem 1:

When a float number is used as start-index, stop-index or step, there is no error reported:

```
>>> a = [1, 2, 3, 4, 5]
---------- Source ----------
1     a = [1, 2, 3, 4, 5]

---------- Run ----------
>>> a[.5:2]
---------- Source ----------
1     a[.5:2]

---------- Run ----------
[1, 2]

>>> a[:.5]
---------- Source ----------
1     a[:.5]

---------- Run ----------
[]
>>> a[::.5]
---------- Source ----------
1     a[::.5]

---------- Run ----------
[]
>>> a[1:1.5]
---------- Source ----------
1     a[1:1.5]

---------- Run ----------
[]
>>> a[1:1.5:.5]
---------- Source ----------
1     a[1:1.5:.5]

---------- Run ----------
[]
```

Python reports `TypeError: slice indices must be integers or None or have an __index__ method` or `TypeError: list indices must be integers or slices, not float` in these cases.

2. If a `RuntimeErrorInvalidIndex` was reported before using a float number as start-index, stop-index or step, SeedLang Shell will crash:

```
>>> a = [1, 2, 3, 4, 5]
---------- Source ----------
1     a = [1, 2, 3, 4, 5]

---------- Run ----------
>>> a[.5]
---------- Source ----------
1     a[.5]

---------- Run ----------
1     a[.5]
: 20220521214810601 Fatal (SeedLang.VM) <> [Ln 1, Col 0 - Ln 1, Col 4] 15: RuntimeErrorInvalidIndex
>>> a[.5:2]
---------- Source ----------
1     a[.5:2]

---------- Run ----------
Process terminated. Assertion failed.
   at SeedLang.Interpreter.VM.Run(Function func) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang/Interpreter/VM.cs:line 49
   at SeedLang.Engine.Run(DiagnosticCollection collection) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang/Engine.cs:line 133
   at SeedLang.Shell.Executor.RunSource(Engine engine, SourceCode source, RunType runType) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang.Shell/Executor.cs:line 76
   at SeedLang.Shell.Executor.Repl(SeedXLanguage language, RunType runType) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang.Shell/Executor.cs:line 32
   at SeedLang.Shell.Program.Run(Options options) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang.Shell/Program.cs:line 71
   at SeedLang.Shell.Program.<>c__DisplayClass1_0.<Main>b__3(Options options) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang.Shell/Program.cs:line 58
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at SeedLang.Shell.Program.Main(String[] args) in /Users/ygwang/src/SeedLang/csharp/src/SeedLang.Shell/Program.cs:line 51
```

2022-05-21 13:48 UTC, wixette commented on csharp/src/SeedLang/Ast/Expressions.cs
> +    // The excluded stop index of the slice. It can be null to indicate the ending of the container.
```suggestion
    // The exclusive stop index of the slice. It can be null to indicate the end of the container.
```

2022-05-21 13:48 UTC, wixette commented on csharp/src/SeedLang/Ast/Expressions.cs
> +    // The start index of the slice. It can be null to indicate the beginner of the container.
```suggestion
    // The start index of the slice. It can be null to indicate the beginning of the container.
```

2022-05-21 13:48 UTC, wixette commented on csharp/src/SeedLang/X/VisitorHelper.cs
> +    // Build slice expressions.
```suggestion
    // Builds slice expressions.
```

2022-05-22 06:19 UTC, codingpotato commented on csharp/src/SeedLang/Ast/Expressions.cs
> +    // The excluded stop index of the slice. It can be null to indicate the ending of the container.
Fixed

2022-05-22 06:21 UTC, codingpotato commented on csharp/src/SeedLang/Ast/Expressions.cs
> +    // The start index of the slice. It can be null to indicate the beginner of the container.
Fixed

2022-05-22 06:22 UTC, codingpotato commented on csharp/src/SeedLang/X/VisitorHelper.cs
> +    // Build slice expressions.
Fixed.

2022-05-22 06:23 UTC, codingpotato commented
The float number and crash issue have been fixed. Please have a review again.

2022-05-22 07:53 UTC, wixette approved these changes
LGTM

2022-05-22 07:53 UTC, merged